using System.Net;
using System.Security.Cryptography;
using EasyImageSharp.PixelFormats;

namespace EasyImageSharp.AI.Tests;

/// <summary>Paths of the tiny ONNX graphs generated by <c>Models/gen_models.py</c>.</summary>
internal static class TestModels
{
    private static readonly string Root = Path.Combine(AppContext.BaseDirectory, "Models");

    public static string IdentityRgb => Get("identity_rgb.onnx");

    public static string IdentityGray => Get("identity_gray.onnx");

    public static string ClassifierFixed => Get("classifier_fixed.onnx");

    public static string ClassifierQuadrant => Get("classifier_quadrant.onnx");

    public static string Upscale2xNearest => Get("upscale2x_nearest.onnx");

    public static string ResidualZeroGray => Get("residual_zero_gray.onnx");

    public static string ConstantHalfGray => Get("constant_half_gray.onnx");

    public static string SaliencyBrightness => Get("saliency_brightness.onnx");

    public static string Get(string fileName)
    {
        string path = Path.Combine(Root, fileName);
        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"Test model '{fileName}' is missing; run Models/gen_models.py.", path);
        }

        return path;
    }
}

/// <summary>Deterministic synthetic images.</summary>
internal static class TestImages
{
    /// <summary>A pseudo-random RGB image (fixed seed) so every pixel differs from its neighbours.</summary>
    public static Image<TPixel> Noise<TPixel>(int width, int height, int seed = 1234)
        where TPixel : unmanaged, IPixel<TPixel>
    {
        var rng = new Random(seed);
        var image = new Image<TPixel>(width, height);
        for (int y = 0; y < height; y++)
        {
            Span<TPixel> row = image.Frames.RootFrame.GetRowSpan(y);
            for (int x = 0; x < width; x++)
            {
                row[x] = TPixel.FromRgba32(new Rgba32((byte)rng.Next(256), (byte)rng.Next(256), (byte)rng.Next(256)));
            }
        }

        return image;
    }

    /// <summary>A smooth two-axis gradient.</summary>
    public static Image<TPixel> Gradient<TPixel>(int width, int height)
        where TPixel : unmanaged, IPixel<TPixel>
    {
        var image = new Image<TPixel>(width, height);
        for (int y = 0; y < height; y++)
        {
            Span<TPixel> row = image.Frames.RootFrame.GetRowSpan(y);
            for (int x = 0; x < width; x++)
            {
                byte r = (byte)(x * 255 / Math.Max(1, width - 1));
                byte g = (byte)(y * 255 / Math.Max(1, height - 1));
                byte b = (byte)((x + y) * 255 / Math.Max(1, width + height - 2));
                row[x] = TPixel.FromRgba32(new Rgba32(r, g, b));
            }
        }

        return image;
    }

    /// <summary>A dark page with one bright square in the given corner (0 = TL, 1 = TR, 2 = BR, 3 = BL).</summary>
    public static Image<Rgb24> CornerPage(int width, int height, int corner)
    {
        var image = new Image<Rgb24>(width, height, new Rgb24(20, 20, 20));
        int w = width / 3;
        int h = height / 3;
        int x0 = corner is 1 or 2 ? width - w : 0;
        int y0 = corner is 2 or 3 ? height - h : 0;
        for (int y = y0; y < y0 + h; y++)
        {
            Span<Rgb24> row = image.Frames.RootFrame.GetRowSpan(y);
            row.Slice(x0, w).Fill(new Rgb24(240, 240, 240));
        }

        return image;
    }

    public static bool PixelsEqual<TPixel>(Image<TPixel> a, Image<TPixel> b)
        where TPixel : unmanaged, IPixel<TPixel>
    {
        if (a.Width != b.Width || a.Height != b.Height)
        {
            return false;
        }

        for (int y = 0; y < a.Height; y++)
        {
            if (!a.Frames.RootFrame.GetRowSpan(y).SequenceEqual(b.Frames.RootFrame.GetRowSpan(y)))
            {
                return false;
            }
        }

        return true;
    }
}

/// <summary>An in-memory HTTP handler that serves scripted responses and records every request.</summary>
internal sealed class FakeHttpHandler : HttpMessageHandler
{
    private readonly Func<HttpRequestMessage, HttpResponseMessage> responder;

    public FakeHttpHandler(Func<HttpRequestMessage, HttpResponseMessage> responder) => this.responder = responder;

    public List<HttpRequestMessage> Requests { get; } = new();

    public int RequestCount => this.Requests.Count;

    /// <summary>A handler that always serves <paramref name="body"/> in full and honours Range requests with 206.</summary>
    public static FakeHttpHandler Serving(byte[] body, bool supportRange = true) => new(request =>
    {
        if (supportRange && request.Headers.Range?.Ranges.FirstOrDefault() is { } range && range.From is { } from)
        {
            if (from >= body.Length)
            {
                return new HttpResponseMessage(HttpStatusCode.RequestedRangeNotSatisfiable);
            }

            var partial = new HttpResponseMessage(HttpStatusCode.PartialContent)
            {
                Content = new ByteArrayContent(body, (int)from, body.Length - (int)from),
            };
            partial.Content.Headers.ContentRange = new System.Net.Http.Headers.ContentRangeHeaderValue(from, body.Length - 1, body.Length);
            return partial;
        }

        return new HttpResponseMessage(HttpStatusCode.OK) { Content = new ByteArrayContent(body) };
    });

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        lock (this.Requests)
        {
            this.Requests.Add(request);
        }

        return Task.FromResult(this.responder(request));
    }
}

/// <summary>A throw-away cache directory removed on dispose.</summary>
internal sealed class TempCache : IDisposable
{
    public TempCache()
    {
        this.Path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "EasyImageSharp.AI.Tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(this.Path);
    }

    public string Path { get; }

    public void Dispose()
    {
        try
        {
            Directory.Delete(this.Path, recursive: true);
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
    }
}

internal static class Hash
{
    public static string Sha256Hex(byte[] data) => Convert.ToHexString(SHA256.HashData(data));

    public static byte[] Bytes(int length, int seed = 7)
    {
        var rng = new Random(seed);
        var data = new byte[length];
        rng.NextBytes(data);
        return data;
    }
}
